### ISSUE TITLE
Problemas al ejecutar

### ISSUE THREAD

**Issue by juanpedromerinodiaz** [bonitadb/engine_bonitadb#1]
Problemas al ejecutar la aplicación:
![WhatsApp Image 2023-12-31 at 7 29 06 PM](https://github.com/bonitadb/engine_bonitadb/assets/25354622/08d3a7f4-c230-455e-b738-d89d12dfcdb4)
![WhatsApp Image 2023-12-31 at 7 28 30 PM](https://github.com/bonitadb/engine_bonitadb/assets/25354622/d7cfef9b-e288-4557-9004-14b0770d0fcb)

**Comment by bonitadb** [comment]
Hola,
Saludos con la nueva liberacion, ese problema se ha resuelto.

![image](https://github.com/bonitadb/engine_bonitadb/assets/154762688/90f56681-d0df-4c02-adc4-d2236b22d211)

Saludosm
